Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,16 +24,16 @@ jobs:
         if: ${{ runner.os != 'Windows' }}
         run: chmod +x ./gradlecw
       - name: build
-        run: ./gradlecw build
+        run: ./gradlecw build --parallel
       - name: capture build artifacts
         uses: actions/upload-artifact@v2
         with:
           name: Artifacts
           path: '**/build/libs/*.jar'
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: JUnit Tests
-          path: '**/build/test-results/test/TEST-*.xml'
-          reporter: java-junit        
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: JUnit Tests
+#          path: '**/build/test-results/test/TEST-*.xml'
+#          reporter: java-junit        
